version: '2.4'

services:
  database:
    extends:
      file: packages/database/docker-compose.yml
      service: database
    volumes:
      - example_database_data:/var/lib/postgresql/data
      - './packages/database/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql'
    healthcheck:
      test: '!</dev/tcp/db/5432'

  server:
    extends:
      file: packages/server/docker-compose.yml
      service: server
    volumes:
      - $PWD:/relay-graphql-monorepo
    healthcheck:
      test: 'node hc.mjs'
      timeout: 3s
    depends_on:
      database:
        condition: service_healthy

  web:
    extends:
      file: packages/web/docker-compose.yml
      service: web
    volumes:
      - $PWD:/relay-graphql-monorepo
    depends_on:
      server:
        condition: service_healthy

  nginx:
    extends:
      file: nginx/docker-compose.yml
      service: nginx
    volumes:
      - ./nginx/.nginx.conf:/etc/nginx/conf.d/nginx.template
    depends_on:
      server:
        condition: service_healthy

volumes:
  example_database_data:
