import { ReactRelayContext } from 'react-relay';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { ThemeProvider } from '@mui/material/styles';

import theme from '../utils/theme';
import { environment } from '../utils/relay';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="UTF-8" />

        <link rel="icon" href="/favicon.ico" />

        <title>Example</title>
      </Head>

      <ThemeProvider theme={theme}>
        <ReactRelayContext.Provider value={{ environment }}>
          <Component {...pageProps} />
        </ReactRelayContext.Provider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
