# .github/workflows/auto-author-assign.yml
name: 'Auto Author Assign'

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.4.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
